node {
   //def mvnHome
   stage('checkout') { // for display purposes
      checkout([$class: 'GitSCM', branches: [[name: '*/master']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'git@github.com:hujianli94/jenkins001.git']]])
   }
   stage('maven Build') {
      echo 'maven build...'
      echo 'maven build...'
      echo 'maven build...'
      echo 'maven build...'
      echo 'maven build...'
      echo 'maven build...'
      echo 'maven build...'
      echo 'maven build...'
      echo 'maven build...'
      echo 'maven build...'
      echo 'maven build...'
   }
   stage('deploy') {
      echo 'deploy...'
      echo 'deploy...'
      echo 'deploy...'
      echo 'deploy...'
      echo 'deploy...'
      echo 'deploy...'
      echo 'deploy...'
      echo 'deploy...'
      echo 'deploy...'
      echo 'deploy...'
      echo 'deploy...'
      echo 'deploy...'
      echo 'deploy...'
      echo 'deploy...'
      echo 'deploy...'
      echo 'deploy...'
   }
   stage('test') {
      echo 'test...'
      echo 'test...'
      echo 'test...'
      echo 'test...'
      echo 'test...'
      echo 'test...'
      echo 'test...'
      echo 'test...'
      echo 'test...'
      echo 'test...'
      echo 'test...'
      echo 'test...'
      echo 'test...'
   }
}
